{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-copycat.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "k8s-copycat.labels" . | indent 4 }}
{{- with .Values.commonLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.serviceAccount.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- $annotations := merge (dict) (default (dict) .Values.commonAnnotations) (default (dict) .Values.serviceAccount.annotations) }}
{{- if $annotations }}
  annotations:
{{ toYaml $annotations | indent 4 }}
{{- end }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
