{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "k8s-copycat.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "k8s-copycat.labels" . | indent 4 }}
{{- with .Values.commonLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.serviceMonitor.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- $annotations := merge (dict) (default (dict) .Values.commonAnnotations) (default (dict) .Values.serviceMonitor.annotations) }}
{{- if $annotations }}
  annotations:
{{ toYaml $annotations | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
{{ include "k8s-copycat.selectorLabels" . | indent 6 }}
  namespaceSelector:
{{- if .Values.serviceMonitor.namespaceSelector }}
{{ toYaml .Values.serviceMonitor.namespaceSelector | indent 4 }}
{{- else }}
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
  endpoints:
    - port: {{ .Values.service.portName }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      scheme: {{ .Values.serviceMonitor.scheme }}
      path: {{ .Values.serviceMonitor.path }}
      {{- with .Values.serviceMonitor.tlsConfig }}
      tlsConfig:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
{{ toYaml . | indent 8 }}
      {{- end }}
  {{- with .Values.serviceMonitor.targetLabels }}
  targetLabels:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
